name: npm audit

on:
  pull_request:
  push:
    branches:
      - master
# on:
#   schedule:
#     - cron: '0 10 * * *'

jobs:
  scan:
    name: npm audit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install dependencies
        run: npm ci
      - uses: oke-py/npm-audit-action@v1.7.3
        with:
          audit_level: high
          production_flag: true
          github_token: ${{ secrets.GITHUB_TOKEN }}
#          issue_assignees: oke-py
          issue_labels: vulnerability,test
          dedupe_issues: true
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Copy files to S3 with the AWS CLI
        run: |
          aws s3 sync . s3://22funnelytics01logs
     

